/*
 * m2factor
 *
 * This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
 */

package smsotp


import "m2factor/models"

/*
 * Interface for the SMSOTP_IMPL
 */
type SMSOTP interface {
    GetCheckSMSBalance (string) (*models.CheckSmsBalanceModel, error)

    GetSendingSMSOTPAutoGeneratedOTP (string, string) (*models.SendingSmsOtpAutoGeneratedOtpModel, error)

    GetSendingSMSOTPCustomOTP (string, string, string) (*models.SendingSmsOtpModel, error)

    GetVerifySMSOTPInput (string, string, string) (*models.VerifyOtpInputModel, error)
}

/*
 * Factory for the SMSOTP interaface returning SMSOTP_IMPL
 */
func NewSMSOTP() SMSOTP {
    return &SMSOTP_IMPL{}
}