/*
 * m2factor
 *
 * This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
 */

package models


/*
 * Structure for the custom type SendTransactionalSmsModel
 */
type SendTransactionalSmsModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SendingVoiceOtpAutoGeneratedOtpModel
 */
type SendingVoiceOtpAutoGeneratedOtpModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckBalanceAddonServicesModel
 */
type CheckBalanceAddonServicesModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SendingSmsOtpAutoGeneratedOtpModel
 */
type SendingSmsOtpAutoGeneratedOtpModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SendingSmsOtpModel
 */
type SendingSmsOtpModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SendingVoiceOtpModel
 */
type SendingVoiceOtpModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type VerifyVoiceOtpInputModel
 */
type VerifyVoiceOtpInputModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckSmsBalanceModel
 */
type CheckSmsBalanceModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckVoiceBalanceModel
 */
type CheckVoiceBalanceModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type VerifyOtpInputModel
 */
type VerifyOtpInputModel struct {
    Status          string          `json:"Status"` //TODO: Write general description for this field
    Details         string          `json:"Details"` //TODO: Write general description for this field
}
