/*
 * m2factor
 *
 * This file was automatically generated for 2Factor by APIMATIC BETA v2.0 on 02/18/2016
 */

package voiceotp


import "m2factor/models"

/*
 * Interface for the VOICEOTP_IMPL
 */
type VOICEOTP interface {
    GetCheckVoiceBalance (string) (*models.CheckVoiceBalanceModel, error)

    GetSendingVOICEOTPAutoGeneratedOTP (string, string) (*models.SendingVoiceOtpAutoGeneratedOtpModel, error)

    GetSendingVoiceOTPCustomOTP (string, int, string) (*models.SendingVoiceOtpModel, error)

    GetVerifyVOICEOTPInput (string, string, string) (*models.VerifyVoiceOtpInputModel, error)
}

/*
 * Factory for the VOICEOTP interaface returning VOICEOTP_IMPL
 */
func NewVOICEOTP() VOICEOTP {
    return &VOICEOTP_IMPL{}
}